### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by Jarmahent** [olefirenko/vue-barcode-reader#1]
Hey! Great library you have it, it works great on desktop and its very reliable. The only problem is that the live video feed doesnt work on mobile. Is there any way to fix this?

**Comment by olefirenko** [comment]
Hi @Jarmahent, in what OS is it happening, iOS or Android? And in which browser? For my project https://parceltrackingapp.com it works without any issues. The known issue on iOS for websites added to home screen as PWA.

**Comment by Jarmahent** [comment]
Thank you for replying @olefirenko Funny enough Im using the library for the exact same reason you are, package tracking! It works on every browser on android except Chrome on IOS due to a webkit issue its been resolved already but thank you!

**Comment by kpetrillo** [comment]
Are you guys still having issues with this on mobile devices? I just tested on your site and it didn't work with a UPS barcode.
