### ISSUE TITLE
No support for TypeScript

### ISSUE THREAD

**Issue by GabySotirova** [olefirenko/vue-barcode-reader#21]

**Comment by julisch94** [comment]
Hey @GabySotirova ! I contributed to DefinitelyTyped.

You can now run:
`yarn add -D @types/vue-barcode-reader`
or
`npm i -D @types/vue-barcode-reader`

I think we can close this issue now.
See here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57509
