### ISSUE TITLE
Media Stream API is not supported

### ISSUE THREAD

**Issue by alejandrotoga02** [olefirenko/vue-barcode-reader#4]
Error throws when I try to see on the mobile

**Comment by alejandrotoga02** [comment]
The problem was on the SSL certificated

**Comment by pedrodgcouto** [comment]
How did you fix this?

**Comment by r3tr0g4m3r** [comment]
Hi, late to the party, i came from [homebox issue 586 ](https://github.com/sysadminsmedia/homebox/issues/586#event-16748812730)

Fixed it serving through a local signed certificate using stunnel, installing using scoop in my case with powershell:

```
scoop install openssl stunnel
cd %UserProfile%
 or
Set-Location -Path $env:ev_psh
cd .\scoop\persist\stunnel\config
```

```
openssl req -x509 -nodes -newkey rsa:2048 -keyout homebox.key -out homebox.crt -days 3650
Get-Content homebox.crt, homebox.key | Set-Content homebox.pem
```

**stunnel.conf**

```
[homebox]
accept  = 443
connect = 127.0.0.1:7745
cert = homebox.pem
TIMEOUTclose = 0
```

`stunnel -start`
