### ISSUE TITLE
Green Screen on Galaxy Tab Active 2

### ISSUE THREAD

**Issue by NGjata** [olefirenko/vue-barcode-reader#57]
Hi, it's strange but it works correctly on my MBP but when i open the demo from a Galaxy Tablet it gives me a green screen with the red line animation working.

* I accepted the camera access from the popup. 
* It seems the app is working generally, the only problem is the green background (it prevents the barcode read)

**Comment by teckel12** [comment]
@NGjata I have the same thing happening on an Amazon Fire tablet.  My guess is that these tablets are not allowing the browser to access the camera device.

**Comment by NGjata** [comment]
@teckel12 sorry for the late response but I think I found the problem. You should try to enable/disable the Vulkan engine on chrome://flags/ . This was giving me a green background. 

The next think I was missing is the fact that chrome doesn't allow the camera to open on unsafe websites, it doesn't even request the camera access in this cases: To skip the checks in test env try to set your current IP in chrome://flags -> Insecure origins treated as secure

Hope these resolve your problem.

**Comment by teckel12** [comment]
@NGjata Thanks!  I've also added it as an Issue in my fork of this library along with your suggestions (which did work for me as well, to give a secondary confirmation).  https://github.com/teckel12/vue-barcode-reader/issues/7
