### ISSUE TITLE
 Cordova iOS application - Opening a barcode reader causes a new screen to appear on top of the existing screen.

### ISSUE THREAD

**Issue by divyeshGondaliya** [olefirenko/vue-barcode-reader#67]
After a recent IOS update, when we open the scanner an additional blank screen pops out apart from the regular scanner screen because of which the scanner functionality doesn't work. Refer attached video

```
<StreamBarcodeReader
          @decode="onDecode"
          @loaded="onLoaded"
        >
</StreamBarcodeReader>
```

https://github.com/olefirenko/vue-barcode-reader/assets/94589861/a2c7401f-0401-44ab-b3b4-c642f7aafd50

**Comment by kissu** [comment]
More context here: https://stackoverflow.com/q/78580470/8816585

**Comment by divyeshGondaliya** [comment]
The answer can be found here: [stackoverflow](https://stackoverflow.com/a/78586201/5362750)
